### ISSUE TITLE
Can't start my Backdoor Instance

### ISSUE THREAD

**Issue by Mr56k** [RecaMedia/Backdoor-Release#2]
Good morning,

I'm trying to install the Backdoor-IDE into my project, but can not get it running. I've read the first issue before and have installed sqlite3, mcrypt but still can not get it to work. 

Do you have any guess what's wrong?

The URL is: http://test02.fits-hosting.de/bkdr/

Thank you in advance!

Kind regards,
Tobias

**Comment by blakie21737** [comment]
Until Shannon can reply with a definitive answer to me it looks like an error with your php config,

The error reads.
Warning: session_save_path(): open_basedir restriction in effect. File(/) is not within the allowed path(s):

See this post for the possible answer: 

https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

Modify the open_basedir settings in your PHP configuration (See Runtime Configuration).

The open_basedir setting is primarily used to prevent PHP scripts for a particular user from accessing files in another user's account. So usually, any files in your own account should be readable by your own scripts.

Example settings via .htaccess if PHP runs as Apache module on a Linux system:

<DirectoryMatch "/home/sites/site81/">
    php_admin_value open_basedir "/home/sites/site81/:/tmp/:/"
</DirectoryMatch>

**Comment by Mr56k** [comment]
Thanks for the answer. The error is now gone. But now I got an "Access denied" when the browser tries to go to /bkdr/api/settings/open but nothing in the server log itself...

**Comment by blakie21737** [comment]
Hmm that's an interesting one!

Not sure of the exact issue although upon investigation i found that if you
navigate to:
http://test02.fits-hosting.de/bkdr/api/settings

It spits you over to:
http://test02.fits-hosting.de/var/www/vhosts/fits-hosting.de/test02.fits-hosting.de/bkdr/api/settings

Possibly a vhost issue, maybe but less probably a HTACCESS or even
permission issue? i'm not 100% sure on that one i'm thinking its with the
vhost file though "Im just an slightly nerdy john doe", although what i
gather it seems to be some kind of unwanted redirection causing the XHR
request to time out.

Its almost there its just that redirection of the bkdr/api/settings folder
causing it not to fully initialize.

**Comment by Mr56k** [comment]
Thanks @blakie21737 ! This is a nice starting point for some further investigations on the weekend. Will get back to you soon if I found the reason for that!

**Comment by RecaMedia** [comment]
Hi @Mr56k, sorry for the delay. I periodically check my GitHub account, but I never receive any notifications from these issues. Thanks @blakie21737 for stepping in and helping out.

I believe I can point you on the right direction. Your problem seems to be an issue with returning the Session Id. If you look at the back and forth that happens with the [reducer](https://github.com/RecaMedia/Backdoor/blob/master/_development/jsx/reducers/global.jsx) and [listener](https://github.com/RecaMedia/Backdoor/blob/master/_development/jsx/main.jsx#L57), you'll see [here](https://github.com/RecaMedia/Backdoor/blob/master/_development/jsx/main.jsx#L111), where the Session Id does not equal Null but is Undefined. Which allows it to continue without the session and resulting in an "Access Denied."

This definitely needs to be corrected on the application side and take into account the possibility of an undefined Session Id.

Hope this helps!

**Comment by RecaMedia** [comment]
@Mr56k I'm going to assume you were able to get this up and running since I haven't heard back. So I'll close this ticket.
