### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by Epicpkmn11** [RecaMedia/Backdoor-Release#4]
When I try to update it gives me a `Download Failed` error, I don't think I have my .htaccess file done correctly, but if I change it to your example I get this:
![2019-01-02 11 57 47](https://user-images.githubusercontent.com/41608708/50604778-af89e580-0e85-11e9-8ad5-4c5a8674a91f.png)
Sorry to make an issue for what I'm sure is some sorta noob problem (I don't do much with webservers), but I was wondering if you had any idea what I'm doing wrong...

I'm pretty sure I do have `Sqlite3` and `Mcrypt` turned on, I'm hosting using AMPPS 3.8 on a Mac mini Core Solo running Mac OS X Server 10.6.8 if that helps

**Comment by RecaMedia** [comment]
Hi @Epicpkmn11, thanks for reaching out. The update function still needs some work from what I recall. This looks like it might be a .htaccess error. Just to be clear, are you having an issue running Backdoor or trying to update Backdoor?

**Comment by Epicpkmn11** [comment]
It runs fine, just the updating is failing for me.

**Comment by Epicpkmn11** [comment]
I'm not really sure how to properly make a .htaccess file, so currently all mine has is a line saying where the error 404 page is... So that's probably at least part of my problem (Sorry to be such a noob about this ;P)

**Comment by RecaMedia** [comment]
Ok, so updating. Are you referring to this:

![capture](https://user-images.githubusercontent.com/4397817/50622496-94e25b80-0edb-11e9-8222-30e50d68694e.PNG)

This feature doesn't currently work. I haven't been on this project for a while due to another project, so I haven't got around to it. Ultimately, a configuration issue seem like the problem. You shouldn't need to create any .htaccess files, as they are already contained within the BKDR files. All you should really need to do is access the BKDR folder from your browser to follow the install wizard.

In your case, if you have it on your hosting within the root directory, then according to your screenshot, it should be http://beastbot2855.com/bkdr/. Which I see, it's there. I've also visited http://beastbot2855.com/main/ and that seems to pull up just fine for me.

**Comment by Epicpkmn11** [comment]
Alright, sorry to bother you then.

**Comment by RecaMedia** [comment]
@Epicpkmn11 no worries 😃
